### ISSUE TITLE
Metric types counters, gauges?

### ISSUE THREAD

**Issue by mscdit** [Shopify/autotuner#5]
Hi guys,

I would like to export the Autotuner metrics, cp.

https://github.com/Shopify/autotuner/blob/09484ec2f0852543a023a111f65cc1f40439505d/lib/autotuner/request_collector.rb#L78

to Prometheus. Prometheus metrics have different types (like gauges, counters ... a gauge can be observed, a counter can be incremented by one, etc.). Can the Autotuner metrics als be classified by those types ... which type regarding which key?

THX & greetings,
mscd

**Comment by peterzhu2118** [comment]
The metrics emitted should be stored gauges (since you want to calculate things like average, percentiles, max, min).

**Comment by peterzhu2118** [comment]
Actually, on Prometheus it should be the histogram type I think. I added a note about this in 7ec2f33af5230dc02cfd3eb7da6cfe63031b805c.

**Comment by peterzhu2118** [comment]
I think it would make sense for that to be a histogram too, since you would want to keep track of the average and max values for heap_pages too.
